import pandas as pd
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)
data = pd.read_csv("https://video.ittensive.com/python-advanced/data-9722-2019-10-14.utf.csv", delimiter=";")
data["District"] = data["District"].str.replace("район ", "").astype("category")
data["AdmArea"] = data["AdmArea"].apply(lambda x: x.split(" ")[0]).astype("category")
data.set_index("YEAR")
data = data[data["YEAR"]=="2018-2019"].reset_index()
data = data.set_index("AdmArea")
fig = plt.figure(figsize=(10, 10))
area = fig.add_subplot(2, 1, 1)
data_area = data["PASSES_OVER_220"].groupby("AdmArea").sum().plot.pie(ax=area, label="")
area2 = fig.add_subplot(2, 1, 2)
data_area2=data.loc["Северо-Западный"].reset_index().set_index("District")
data_area2 = data_area2["PASSES_OVER_220"].groupby("District").sum()
total = sum(data_area2)
data_area2.plot.pie(ax=area2, label="", autopct=lambda x:int(total*x/100))
plt.show()
print(data_area2)